---
- name: Create a user on Windows
  hosts: hosts
  tasks:
    - name: Ensure the user exists
      ansible.windows.win_user:
        name: "new_user"
        password: "Password123!"
        groups:
          - "Administrators"
        state: present
        password_never_expires: yes
        update_password: always
