---
- name: Creating Purple Team Lab With Automations
  hosts: win_host
  gather_facts: yes
  vars:
     hostname: "{{ ansible_hostname }}"
     ansible_winrm_operation_timeout_sec: 1800
     ansible_winrm_read_timeout_sec: 300
     ansible_winrm_operation_timeout_sec: 200

  tasks:
  - name: Create new domain in a new forest on the target host
    microsoft.ad.domain:
      dns_domain_name: pwc.com
      safe_mode_password: Password1!
      reboot: false

  - name: reboot | Rebooting Server
    win_reboot:
      connect_timeout: 15
      post_reboot_delay: 15

  - name: Create new Windows domain in a new forest with specific parameters
    microsoft.ad.domain:
      create_dns_delegation: false
      database_path: C:\Windows\NTDS
      dns_domain_name: pwc.com
      domain_mode: Win2012R2
      domain_netbios_name: PWC
      forest_mode: Win2012R2
      safe_mode_password: Password1!
      sysvol_path: C:\Windows\SYSVOL
      install_dns: true
    register: domain_install

  - name: reboot | Rebooting Server
    win_reboot:
      connect_timeout: 15
      post_reboot_delay: 15

  - name: Creating users and groups
    ansible.windows.win_powershell:
      script: |
        $script = (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/wazehell/vulnerable-AD/master/vulnad.ps1')
        Invoke-Expression -Command $script
        Invoke-VulnAD -UsersLimit 20 -DomainName 'pwc.com'
...
