---
- name: Playbook to install Microsoft AD collection
  hosts: all
  become: yes
- name: Install Microsoft AD collection
  ansible.builtin.command:
    cmd: ansible-galaxy collection install microsoft.ad
