---
- name: Playbook to install Microsoft AD collection
  hosts: all
  become: yes

  tasks:
  - name: Install Microsoft AD collection
    ansible.builtin.shell:
      cmd: ansible-galaxy collection install microsoft.ad
